on:
  push:
    branches:
      - main

jobs:
  website:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 6.0.2
          run_install: true
      - run: cp README.md website/index.md

#       - run: pnpm --filter demo-* build
      
#       - run: cp -r packages/demo-counter/dist website/demo-counter
#       - run: cp -r packages/demo-flat-form/dist website/demo-flat-form
#       - run: cp -r packages/demo-nested-form/dist website/demo-nested-form
#       - run: cp -r packages/demo-todo-local/dist website/demo-todo-local
#       - run: cp -r packages/demo-animation/dist website/demo-animation
#       - run: cp -r packages/demo-todo-client/dist website/demo-todo-client
#       - run: cp -r packages/demo-server-side-render/dist website/demo-server-side-render
#       - run: cp -r packages/demo-nested-resource/dist website/demo-nested-resource
      
      - name: Deploy to vue-db.js.org
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_dir: ./website
          enable_jekyll: true
          
      - name: Deploy to autonomy.design
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_dir: ./website
          enable_jekyll: true
          external_repository: taowen/modularization-examples
          publish_branch: master
          destination_dir: vue-db
